# Generated by Django 4.2.13 on 2024-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskManage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(db_index=True, max_length=100)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("priority", models.PositiveBigIntegerField(default=1)),
                ("severity", models.PositiveBigIntegerField(default=1)),
                ("deadline", models.DateField(db_index=True)),
                ("assignee_note", models.TextField(blank=True, null=True)),
                (
                    "complaints_received_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("portal", "Portal"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "completion_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("portal", "Portal"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ("priority", "severity", "-deadline"),
            },
        ),
    ]
