# Generated by Django 4.2.13 on 2024-05-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmanage",
            name="completion_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resolved_successfully", "Resolved Successfully"),
                    ("incomplete_information", "Incomplete Information"),
                    ("parts_equipment_needed", "Parts/Equipment Needed"),
                    ("client_unavailable", "Client Unavailable"),
                    ("not_serviceable", "Not Serviceable"),
                    ("out_of_scope", "Out of Scope"),
                    ("duplicate_task", "Duplicate Task"),
                    ("technical_limitation", "Technical Limitation"),
                    ("client_requested_delay", "Client-Requested Delay"),
                ],
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),
    ]
